apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  selector:
    matchLabels:
      run: tomcat
  replicas: 2
  template:
    metadata:
      labels:
        run: tomcat
    spec:
      containers:
      - name: tomcat
        image: vik2595/tomcat:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/ubuntu/deployment
          name: deployment
      volumes:
      - name: deployment
        persistentVolumeClaim:
          claimName: tomcatclaim

---
apiVersion: v1
kind: Service
metadata:
  name: tomcatservice
spec:
  selector:
    app: tomcat
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcatservice
spec:
  selector:
    app: tomcat
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30033