apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcatvolume
  namespace: tomcat
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/jenkins/workspace/CI/target"