AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetParameter:
    Type: String
    Default: 'subnet-05d2a07cb78b1745a'
    AllowedValues:
      - 'subnet-05d2a07cb78b1745a'
      - 'subnet-068d751348b98cf1e'
    Description: Choose Subnet 1a - 451, 1b - f1e
Resources:
  SplunkForwarder1:
    Type: 'AWS::EC2::Instance'
    Properties:
      SubnetId: !Ref SubnetParameter
      ImageId: ami-08523c5075ba75813
      InstanceType: t2.micro
      KeyName: vikTech
      SecurityGroupIds: 
        - sg-0db8e0fe5b518f6fb
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 10
      Tags:
        -
          Key: profile
          Value: vik
        -
          Key: Name
          Value: SplunkForwarder1
      UserData: 
          !Base64 |
          #!/bin/bash
          sudo yum update
          mkdir /home/ec2-user/forwarder


Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - SplunkForwarder1
        - PublicIp
    Description: Server's PublicIp Address