AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetParameter:
    Type: String
    Default: 'subnet-05d2a07cb78b1745a'
    AllowedValues:
      - 'subnet-05d2a07cb78b1745a'
      - 'subnet-068d751348b98cf1e'
    Description: Choose Subnet 1a - 45a, 1b - f1e,
Resources:
  KubeMaster:
    Type: 'AWS::EC2::Instance'
    Properties:
      SubnetId: !Ref SubnetParameter
      ImageId: ami-08523c5075ba75813
      InstanceType: t2.micro
      KeyName: vikTech
      SecurityGroupIds: 
        - sg-0db8e0fe5b518f6fb
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 10
      Tags:
        -
          Key: profile
          Value: vik
        -
          Key: Name
          Value: KubeMaster
      UserData: 
          !Base64 |
          #!/bin/bash
          sudo yum update
          sudo yum install java-1.8.0-openjdk-devel -y
          sudo yum install git -y
          sudo yum install amazon-cloudwatch-agent -y
          sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
          sudo dnf install docker-ce-3:19.03.13-3.el8 -y
          sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
          EOF
          sudo setenforce 0
          sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
          sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
          sudo systemctl enable --now kubelet
          sudo yum update
          systemctl daemon-reload
          systemctl start docker
          systemctl start kubelet
          mkdir ./Kubemaster
          
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - KubeMaster
        - PublicIp
    Description: Server's PublicIp Address