AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetParameter:
    Type: String
    Default: 'subnet-05d2a07cb78b1745a'
    AllowedValues:
      - 'subnet-05d2a07cb78b1745a'
      - 'subnet-068d751348b98cf1e'
    Description: Choose Subnet 1a - 45a, 1b - f1e,
Resources:
  Jenkins:
    Type: 'AWS::EC2::Instance'
    Properties:
      SubnetId: !Ref SubnetParameter
      ImageId: ami-0c9bfc21ac5bf10eb
      InstanceType: t2.micro
      KeyName: vikTech
      SecurityGroupIds: 
        - sg-0db8e0fe5b518f6fb
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      Tags:
        -
          Key: profile
          Value: vik
        -
          Key: Name
          Value: jenkins
      UserData: 
          !Base64 |
          #!/bin/bash
          sudo yum update
          sudo yum install java-1.8.0-openjdk-devel -y
          sudo wget -O /etc/yum.repos.d/jenkins.repo \
          https://pkg.jenkins.io/redhat-stable/jenkins.repo
          sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
          sudo yum install jenkins -y
          sudo yum install git -y
          sudo yum install amazon-cloudwatch-agent -y
          wget https://apache.mirror.colo-serv.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          sudo tar -xvf apache-maven-3.6.3-bin.tar.gz -C /opt
          export M2_HOME=/opt/apache-maven-3.6.3
          export M2=$M2_HOME/bin
          export PATH=$M2:$PATH
          sudo systemctl daemon-reload
          sudo systemctl start jenkins

  
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - Jenkins
        - PublicIp
    Description: Server's PublicIp Address